service: hello-lambda

frameworkVersion: '>=3.0.0'
provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: handler.hello_world
    events:
      - http:
          path: dev-hello-lambda
          method: get

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .github/**
    - README.md
    - deploy.yml